---
title: "HandTracker"
output: html_document
---

```{r horizontal data}
dataIndex = 0
dataPath = paste("Noor_DATAFORHORIZONTAL_data", dataIndex,".txt", sep = "")

if(file.exists(dataPath))
{
  df = read.table(dataPath, header = TRUE)
}
```

```{r}
install.packages("plot3D")
library("plot3D")
```

```{r horizontal three axes}
x <- df$x
y <- df$y
z <- df$z
# Compute the linear regression (z = ax + by + d)
fit <- lm(z ~ x + y)
# predict values on regular xy grid
grid.lines = 26
x.pred <- seq(min(x), max(x), length.out = grid.lines)
y.pred <- seq(min(y), max(y), length.out = grid.lines)
xy <- expand.grid( x = x.pred, y = y.pred)
z.pred <- matrix(predict(fit, newdata = xy), 
                 nrow = grid.lines, ncol = grid.lines)
# fitted points for droplines to surface
fitpoints <- predict(fit)
# scatter plot with regression plane
scatter3D(x, y, z, pch = 18, cex = 2, 
    theta = 120, phi = 20, ticktype = "detailed",
    xlab = "x", ylab = "y", zlab = "z",  
    surf = list(x = x.pred, y = y.pred, z = z.pred,  
    facets = NA, fit = fitpoints))

#scatter with no line
scatter3D(x, y, z, phi = 20, bty = "g",
        pch = 20, cex = 2, ticktype = "detailed")
```

```{r horizontal two axes}
# compute ONLY along two axes
# decline of 4 units across across 0.2 units --> slope of 20 degrees from horizontal downwards!

plot(z, y)
abline(h = 21)
abline(h = 25)
```

```{r vertical data}
dataIndexVert = 0
dataPathVert = paste("Noor_DATAFORVERTICAL_data", dataIndexVert,".txt", sep = "")

if(file.exists(dataPathVert))
{
  df_vert = read.table(dataPathVert, header = TRUE)
}
```

```{r horizontal three axes}
x <- df_vert$x
y <- df_vert$y
z <- df_vert$z
# Compute the linear regression (z = ax + by + d)
fit <- lm(z ~ x + y)
# predict values on regular xy grid
grid.lines = 26
x.pred <- seq(min(x), max(x), length.out = grid.lines)
y.pred <- seq(min(y), max(y), length.out = grid.lines)
xy <- expand.grid( x = x.pred, y = y.pred)
z.pred <- matrix(predict(fit, newdata = xy), 
                 nrow = grid.lines, ncol = grid.lines)
# fitted points for droplines to surface
fitpoints <- predict(fit)
# scatter plot with regression plane
scatter3D(x, y, z, pch = 18, cex = 2, 
    theta = 120, phi = 20, ticktype = "detailed",
    xlab = "x", ylab = "y", zlab = "z",  
    surf = list(x = x.pred, y = y.pred, z = z.pred,  
    facets = NA, fit = fitpoints))

#scatter with no line
scatter3D(x, y, z, phi = 20, bty = "g",
        pch = 20, cex = 2, ticktype = "detailed")
```

```{r vertical two axes}
# compute ONLY along two axes
# decline of 4 units across across 0.2 units --> slope of 20 degrees from horizontal downwards!

plot(x, z)
abline(h = 21)
abline(h = 25)
```